### ISSUE TITLE
Errors at Capella 7.0 startup

### ISSUE THREAD

**Issue by mPorhel** [eclipse-capella/capella#2852]
Reproductible on macOs at least.

- Download the latest Capella 7.0 stable (7.0.0-S20240320)
- Extract Capella
  - on macOs: remove quarantine status with  `xattr -d com.apple.quarantine Capella.app`
- Launch Capella
- Select a new workspace
- Open the Error log view: 

![Errors at startup](https://github.com/eclipse-capella/capella/assets/1019672/6e392fc8-d3b4-4269-a0b4-4a1970a6cfca)

**Comment by mPorhel** [comment]
One error seems to come from Mylyn integration

Seven errors are related to Capella "re" subcommands:
- Impacted commands
  - org.polarsys.capella.common.re.ui.subcommands.handlers.SelectionDependenciesScopeHandler.setEnabled(SelectionDependenciesScopeHandler.java:45) 
  - at org.polarsys.capella.common.re.ui.subcommands.handlers.DeleteHandler.setEnabled(DeleteHandler.java:64)
  -  org.polarsys.capella.common.re.ui.subcommands.handlers.BrowseScopeHandler.setEnabled(BrowseScopeHandler.java:35)
   - org.polarsys.capella.common.re.ui.subcommands.handlers.ChildrenScopeHandler.setEnabled(ChildrenScopeHandler.java:41) 
 - org.polarsys.capella.common.re.ui.subcommands.handlers.DeleteHandler.setEnabled(DeleteHandler.java:64)
 - org.polarsys.capella.common.re.ui.subcommands.handlers.AddElementsScopeHandler.setEnabled(AddElementsScopeHandler.java:56)
  -  org.polarsys.capella.common.re.ui.subcommands.handlers.SuffixableHandler.setEnabled(SuffixableHandler.java:61)
- Full stack: (only the thirf line changes between the seven errors, see list of impacted commands in the previous bullet point)
```
java.lang.ClassCastException: class java.lang.Object cannot be cast to class org.eclipse.jface.viewers.ISelection (java.lang.Object is in module java.base of loader 'bootstrap'; org.eclipse.jface.viewers.ISelection is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1309a7d9)
	at org.polarsys.capella.common.re.ui.subcommands.handlers.SubCommandHandler.getSelectedObjects(SubCommandHandler.java:58)
	at org.polarsys.capella.common.re.ui.subcommands.handlers.SuffixableHandler.setEnabled(SuffixableHandler.java:61)
	at org.eclipse.ui.internal.handlers.HandlerProxy.setEnabled(HandlerProxy.java:229)
	at org.eclipse.ui.internal.handlers.HandlerProxy.loadHandler(HandlerProxy.java:344)
	at org.eclipse.ui.internal.handlers.HandlerProxy.setEnabled(HandlerProxy.java:227)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.setEnabled(E4HandlerProxy.java:133)
	at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.setEnabled(HandlerServiceHandler.java:84)
	at org.eclipse.core.commands.Command.setEnabled(Command.java:856)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.canExecute(HandlerServiceImpl.java:179)
	at org.eclipse.ui.internal.quickaccess.providers.CommandProvider.retrieveCommand(CommandProvider.java:102)
	at org.eclipse.ui.internal.quickaccess.providers.CommandProvider.getElements(CommandProvider.java:85)
	at org.eclipse.ui.internal.quickaccess.QuickAccessProvider.getElementsSorted(QuickAccessProvider.java:83)
	at org.eclipse.ui.internal.quickaccess.QuickAccessContents$3.runInUIThread(QuickAccessContents.java:397)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:148)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4368)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3991)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.polarsys.capella.core.platform.sirius.ui.app.CapellaApplication.start(CapellaApplication.java:118)
```

**Comment by mPorhel** [comment]
Situation is better with [v7.0.0-S20240521](https://github.com/eclipse-capella/capella/releases/tag/v7.0.0-S20240521)

![IssuesAtStartup20240522](https://github.com/eclipse-capella/capella/assets/1019672/a89ddba2-bdf6-4274-a8bc-fbe4282cac4e)

No more "Capella" related method/classes in stack traces.

Logged error seems to come from async ui job executed after resources disposal:
* Exception occurred while rendering: org.eclipse.mylyn.tasks.ui.trim.container=org.eclipse.e4.ui.model.application.ui.menu.impl.ToolBarImpl@172b39c3 (tags: [Draggable], contributorURI: null) (widget: ImageBasedFrame {} [layout=null], renderer: org.eclipse.e4.ui.workbench.renderers.swt.ToolBarManagerRenderer@74575124, toBeRendered: true, onTop: false, visible: false, containerData: null, accessibilityPhrase: null)
* IWorkbenchSite.getShell() was called after part disposal: PartSite(id=org.eclipse.ui.internal.introview,pluginId=org.eclipse.ui,registeredName=Welcome,hashCode=1065320362)
* Problems occurred when invoking code from plug-in: "org.eclipse.e4.ui.workbench.swt", org.eclipse.swt.SWTException: Widget is disposed

They are logged only at the first start of a new workspace.
